version: "3.8"

services:
  auth_db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
    restart:
      always

  auth_backend:
    build: 
      context: ./backend
    env_file: 
      - .env
      - .jwt_env

    ports:
      - 1338:8000
    restart:
      always
